% -------------------------------------------------------------------
%  Generated by MATLAB on 13-Sep-2022 07:09:00
%  MATLAB version: 9.7.0.1190202 (R2019b)
% -------------------------------------------------------------------
addpath('includes');


angle       = 45;             	% Угол вылет в градусах
hits        = [1,0.4,1];       	% Желаемый удар в ноги, в метрах высоты
StartSpeeds = [9.2,10,10.8];	% Скорость в м/с на кроке вылета
starts      = [6,8,10];       	% X начиная с которого отрисовывать углы
centerHeigt = 1;            % Высота центра тяжести от покрытия


G        	= 9.807;            % Ускорение свободного падения
angle    	= angle*pi/180;

refreshed = false;
for n = 1:length(StartSpeeds)

    speed  	= StartSpeeds(n);
    hit     = hits(n);
    start   = starts(n) ;

    hitSpeed	= sqrt(2*G*hit);        % Скорость по нормали к приземлению, даёт ощущение удара

    res     = sim('flight_model');

    Xs      = res.X.Data;
    Ys      = res.Y.Data;
    angles  = res.angle.Data;
    speeds  = res.speed.Data;

    plot(Xs,Ys);
    if not(refreshed)
       refreshed = true;
       hold on
    end

    step    = 0.4;  % даннные для отрисовки
    len     = 2;
    if hit > 0
        for i=1:length(Xs)
            if Xs(i)>start
                ang = asin(hitSpeed/speeds(i)) + angles(i);
                draw_angle(Xs(i),Ys(i),ang);

                start   = start + step;
            end
        end
    end
end
axis image

xl      = xlim();
yl      = ylim();
rangeX  = max(xl) - min(xl);
rangeY  = max(yl) - min(yl);
padding = max(rangeX,rangeY)*0.07;
xlim([xl(1)-padding,xl(2)+padding]);
ylim([yl(1)-padding,yl(2)+padding]);

title('Геометрия полёта');
xlabel('Дистанция(м)')
ylabel('Высота(м)')
hold off
